# Generated by Django 5.2.17 on 2026-09-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=80)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('company', models.CharField(max_length=120)),
                ('package_lpa', models.DecimalField(decimal_places=2, max_digits=7)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('In Process', 'In Process'), ('Not Placed', 'Not Placed')], default='In Process', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
