# Generated by Django 5.2.17 on 2026-09-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='package_lpa',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
